# Generated by Django 5.2.1 on 2025-06-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtuser_post',
            name='link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='wtuser_post',
            name='topic',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
