# Generated by Django 5.2.1 on 2025-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_wtuser_post_link_wtuser_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtuser_post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wtuser_post',
            name='link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
