# Generated by Django 5.2.1 on 2025-06-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_posttag_posturl_wtuserpost_delete_wtuser_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtuserpost',
            name='link',
        ),
        migrations.AddField(
            model_name='posturl',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='post_app.wtuserpost'),
        ),
        migrations.AlterField(
            model_name='posturl',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
