# Generated by Django 5.2.1 on 2025-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_remove_wtuserpost_link_posturl_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttag',
            name='tag_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
