# Generated by Django 5.2.1 on 2025-06-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_posttag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtuserpost',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='posturl',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.DeleteModel(
            name='PostUrl',
        ),
    ]
