# Generated by Django 5.2.1 on 2025-06-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_wtuser_profile_profile_completed_and_more'),
        ('post_app', '0008_remove_wtuserpost_tags_remove_posturl_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtuserpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core_app.wtuser_profile'),
        ),
    ]
