# Generated by Django 5.2.1 on 2025-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_alter_wtuserpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wtuserpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post_app.tag'),
        ),
    ]
