# Generated by Django 5.2.1 on 2025-06-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_wtuser_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wtuser_profile',
            name='last_name',
            field=models.CharField(help_text='Прізвище', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wtuser_profile',
            name='name',
            field=models.CharField(help_text='Ім’я', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wtuser_profile',
            name='username',
            field=models.CharField(help_text='Ім’я користувача', max_length=200, null=True),
        ),
    ]
