# Generated by Django 5.2.1 on 2025-06-13 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_wtuser_profile_profile_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('old_password', models.CharField(max_length=200)),
                ('new_password', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_card', to='core_app.wtuser_profile')),
            ],
        ),
    ]
